"""Initial Migration

Revision ID: 77217c633bf6
Revises: a3032c881fba
Create Date: 2019-02-11 21:14:08.369052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77217c633bf6'
down_revision = 'a3032c881fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
