"""Initial Migration

Revision ID: e2aa407c0fc3
Revises: d269b92ec16d
Create Date: 2019-02-13 04:23:16.392410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2aa407c0fc3'
down_revision = 'd269b92ec16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'posted')
    op.add_column('pitches', sa.Column('author', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('category', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('content', sa.String(), nullable=True))
    op.drop_constraint('pitches_user_id_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'users', ['author'], ['id'])
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'likes')
    op.drop_column('pitches', 'pitch_content')
    op.drop_column('pitches', 'pitch_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitch_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_user_id_fkey', 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'content')
    op.drop_column('pitches', 'category')
    op.drop_column('pitches', 'author')
    op.add_column('comments', sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
